# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

# This is from git hub repo

trigger:
- main

pool:
  name: default

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
#- task: NuGetToolInstaller@1

#- task: NuGetCommand@2
 # inputs:
  #  restoreSolution: '$(solution)'
#- task: UseDotNet@2
#  inputs:
 #   version: '9.x'
- task: DotNetCoreCLI@2
  displayName: 'Restore dependencies'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: "testing and code coverage"
  inputs:
    command: 'test'
    projects: '**/webtest.csproj'
    arguments: '/p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=./Mycoverage/'
    publishTestResults: true

- task: PublishCodeCoverageResults@2
  displayName: "publish code coverage results"
  inputs:
   summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/Mycoverage/coverage.cobertura.xml'



- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '--configuration $(buildConfiguration) -o $(Build.ArtifactStagingDirectory)'





